apiVersion: v1
kind: Service

metadata:
  name: hotstar-devsecops-service

spec:
  selector:
    app: hotstar-devsecops

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer
