name: SecureFlow-CD-Pipeline

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      # Configure kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      # Verify Cluster
      - name: Verify Cluster
        run: |
          kubectl get nodes

      # Deploy Application
      - name: Deploy to EKS
        run: |
          kubectl apply -f K8S/deployment.yml
          kubectl apply -f K8S/service.yml

      # Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/hotstar-devsecops

      # Check Pods
      - name: Get Pods
        run: |
          kubectl get pods -o wide

      # Check Services
      - name: Get Services
        run: |
          kubectl get svc

      # Success Message
      - name: Deployment Successful
        run: echo "Application deployed successfully"
