name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
        | docker login --username AWS \
        --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }} .

    - name: Tag Image
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Push Image
      run: |
        docker push $IMAGE_URI

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
        --region ${{ secrets.AWS_REGION }} \
        --name ${{ secrets.EKS_CLUSTER_NAME }}

    # 🔥 KEY STEP (DO NOT MISS)
    - name: Deploy to EKS using existing YAML
      run: |
        kubectl apply -f k8s/

        kubectl set image deployment/hotstar-deployment \
        hotstar=$IMAGE_URI

        kubectl rollout status deployment/hotstar-deployment
